version: '3'
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - ./build:/app/build
            - ./public:/app/public
            - ./src:/app/src
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./build:/app/build
            - ./public:/app/public
            - ./src:/app/src
        command: ["npm", "run", "test"]